### ISSUE TITLE
Use a wildcard for work location

### ISSUE THREAD

**Issue by jstride** [malcolmrigg/WizardClock#2]
More than one person in our house 'works', zones have to have unique names in Home Assistant so would be good if the search for work could be work* rather than add additional locations to the clock

**Comment by malcolmrigg** [comment]
I've been using zones with the same friendly_name without any problem - we have several "Work" locations set up which only show up in the clock once. 

Due to the way locations are added to the clock on the fly I'm not sure how we could configure what you're suggesting, though I can see it being useful (it would be good being able to have the zones named differently for other uses, but grouped under a single "Work" for the clock)... any ideas?

**Comment by jstride** [comment]
I'll try again, it seemed to blast my friendly names so must have been something in the config!
